import type { Metadata } from "next";
import { Fredoka as Fredoka_One, Inter } from "next/font/google";
import "./globals.css";
import PageTransition from "@/components/page-transition";
import Navbar from "@/components/navbar";

const fredokaOne = Fredoka_One({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--font-fredoka",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fredokaOne.variable} ${inter.variable} antialiased`}>
        <Navbar />
        <div className="overflow-x-hidden bg-gradient-to-br from-amber-50 via-orange-50 to-yellow-50">
          <PageTransition>{children}</PageTransition>
        </div>
      </body>
    </html>
  );
}
